- src/app/api/delegates/getDelegates.ts
> solve voting power relative to quorum division bug

- src/app/delegates/page.jsx
- src/components/Delegates/DelegatesFilter/DelegatesFilter.jsx
- src/components/Delegates/DelegatesSearch/DelegatesSearch.jsx
- src/components/shared/Form/TextInputWithTooltip.tsx
- Build Search field into Delegates Index page
> search delegates done

- src/app/lib/hooks/useIsAdvancedUser.ts
- src/components/Delegates/DelegateCardList/DelegateCardList.tsx
- src/components/Dialogs/AdvancedDelegateDialog/SubdelegationRow.tsx
- In production only addresses in the allowlist can see the advanced flow
- fix build
> Allowlist + fix build

- src/app/lib/hooks/useIsAdvancedUser.ts
- src/lib/governorUtils.ts
- src/lib/proposalUtils.ts
Move server action in server library
> Fix proposal page

- src/app/api/votes/getVotes.ts
- paginate every 10 past votes
- hotfix getVotesForDelegate
> add pagination 10 and hotfix getVotesForDelegate

- src/components/Dialogs/AdvancedDelegateDialog/AdvancedDelegateDialog.tsx
- src/components/Dialogs/AdvancedDelegateDialog/SubdelegationRow.tsx
Solving a regression introduced in #52
> wojeth/agora-1487 Display previously delegated balances during advanced delegation

- src/app/api/statements/getStatements.ts
- src/app/api/votes/getVotes.ts
- src/app/delegates/[addressOrENSName]/page.jsx
- src/components/Delegates/DelegateCard/DelegateCard.jsx
- src/components/Delegates/DelegateCardList/DelegateCardList.tsx
- src/components/Delegates/Delegations/DelegationsContainer.tsx
Optimizations:
- Votes query: apply proposals & voter filter directly on FDWs
- Delegate page: use `getItem` instead of `query` on read from Dynamo + parallelize loading
PS. sorting for votes query is hardcoded as I was unable to correctly parse sort order into the raw prisma string
> Optimisations

- src/app/delegates/[addressOrENSName]/page.jsx
- src/app/delegates/page.jsx
- src/components/Delegates/DelegateCard/AdvancedDelegateButton.tsx
- src/components/Delegates/DelegateCard/DelegateActions.tsx
- src/components/Delegates/DelegateCard/DelegateCard.jsx
- src/components/Delegates/DelegateCard/DelegateCardClient.tsx
- src/components/Delegates/DelegateCardList/DelegateCardList.tsx
- src/components/Proposals/Proposal/OPStandardProposalStatus.jsx
- src/components/Proposals/ProposalPage/OPProposalPage/OPProposalOptimisticPage.jsx
- src/components/Proposals/ProposalPage/OPProposalPage/OPProposalPage.tsx
- src/components/Votes/ProposalVotesList/ProposalVotesList.jsx
- src/components/Votes/VoterHoverCard.tsx
disables advance delegation to self or delegators
fix: linear issue 1499
> disable circular delegation

- src/components/Delegates/DelegateVotes/StandardVoteContainer.jsx
> wojeth/agora-1466 Add colors to past votes

- src/components/Votes/ProposalVotesList/ProposalVotesList.jsx
- src/components/Votes/ProposalVotesList/proposalVotesList.module.scss
> fix: styling

- src/components/Header/DesktopProfileDropDown.tsx
- src/components/Header/MobileProfileDropDown.tsx
Here is the preview link https://agora-next-7ip0b6kr8-voteagora.vercel.app/
> fix cursor pointer

- src/components/Layout/PageContainer.tsx
Here is the preview link: https://agora-next-nrg5wq7nt-voteagora.vercel.app/
> Frh tablet responsive broken 1468

- src/app/api/proposals/getNeedsMyVoteProposals.ts
- src/app/lib/prisma.ts
- src/app/page.jsx
- src/components/Proposals/NeedsMyVoteProposalsList/NeedsMyVoteProposalsList.jsx
- src/components/Proposals/NeedsMyVoteProposalsList/needsMyVoteProposalLists.module.scss
video: https://www.loom.com/share/0b2bc957ac3e40619cc0ef6adca00e82
note: it takes a moment to load. @yitongzhang lmk if i should place a skeleton there
> wojeth/agora-1315 Needs my vote

- src/app/admin/actions.ts
- src/app/admin/page.tsx
- src/components/Admin/AdminForm.tsx
- src/components/Admin/ProposalTypeSettings.tsx
Preview link: https://agora-next-cmajw70di-voteagora.vercel.app/
Linear issue: https://linear.app/agora-app/issue/AGORA-1553/cache-is-not-being-reset-on-the-admin-page
> Cache is not being reset on the Admin page

- src/app/api/votes/getVotes.ts
- src/components/Proposals/ProposalPage/OPProposalApprovalPage/ApprovalVotesPanel/ApprovalVotesPanel.tsx
- src/components/Proposals/ProposalPage/OPProposalApprovalPage/OPProposalApprovalPage.tsx
- src/components/Proposals/ProposalPage/OPProposalPage/OPProposalOptimisticPage.jsx
- src/components/Proposals/ProposalPage/OPProposalPage/OPProposalPage.tsx
- src/components/Votes/ApprovalProposalVotesList/ApprovalProposalVotesList.tsx
- src/components/Votes/ProposalVotesList/ProposalVotesList.jsx
video: https://www.loom.com/share/31b75366e11644aea44a1beaf2914268?sid=b28e6db6-de69-4d77-840c-f4ced2be4b57
request for test: display your vote on optimistic or a standard proposal if you voted twice (couldn't personally recreate)
> wojeth/agora-1520 Add your vote at the top of the proposal votes list

- src/components/Header/ConnectButton.tsx
- src/components/Header/Header.jsx
- src/components/Header/header.module.scss
video: https://www.loom.com/share/c4e3e4250c98428ea074906fac564c53?sid=2afe59c6-0aaf-4ff2-93ae-11c2496e4e8a
> Fix an awkward layout shift on first render

- prisma/schema.prisma
- src/components/Header/DesktopConnectButton.tsx
- src/components/Header/DesktopProfileDropDown.tsx
Hi @yitongzhang 
Here is the preview link: https://agora-next-27faik5mh-voteagora.vercel.app/. 
It also solves an HTML error by which a button was a descendant of another button.
Thank you!
> Fix wallet connect button styling

- next.config.js
Here is the preview link: https://agora-next-bnwxhdmr5-voteagora.vercel.app/
This is only for delegates/[addressOrEnsName] page
> redirect delegate page to delegates

- src/components/Proposals/ProposalPage/OPProposalApprovalPage/OPProposalApprovalPage.module.scss
very small change! Fixing an overflow issue where the content overflows out of it's container since the container has a fixed height.
> Resolves button overflow issue on approval proposal voting card

- src/app/api/analytics/top/delegates/getTopDelegateWeighs.ts
...need to figure out how to conform to existing patterns.  
Right now, I'm wondering if anything else broke.
> Force lower case in top delegates query

- src/app/api/common/delegates/getDelegates.ts
Attempts to resolve issue here: 
https://voteagora.slack.com/archives/C06STQ1C753/p1720629928543569?thread_ts=1720629918.791039&cid=C06STQ1C753
> Fixes incorrect F/A/A counts

- src/app/api/analytics/metric/[metric_id]/[frequency]/getMetricsTS.ts
- src/app/info/components/ChartGovernanceRequiredDelegates.tsx
> Fix labels and dates on Delegates Needed Chart

- src/components/Header/DesktopConnectButton.tsx
- src/components/Header/MobileProfileDropDown.tsx
| before | after |
|----------|----------|
| <img width="612" alt="Screenshot 2024-07-31 at 10 55 27 AM" src="https://github.com/user-attachments/assets/0fe0a2ee-6922-40d2-b4bb-9627de2cef1c"> | <img width="612" alt="Screenshot 2024-07-31 at 10 55 14 AM" src="https://github.com/user-attachments/assets/5884a5fe-9d4d-41b0-b411-b1133939398f"> |
> Resolves mobile issue

- src/app/info/components/InfoAbout.tsx
- src/lib/tenant/configs/ui/cyber.ts
> Cyber copy update

- src/lib/tenant/configs/contracts/etherfi.ts
- src/lib/tenant/configs/ui/etherfi.ts
> Updated Etherfi provider and added allow-listed delegates

- src/app/info/components/GovernorSettingsParams.tsx
- src/components/Admin/GovernorSettings.tsx
- src/lib/blockTimes.ts
> Governor voting delay / period saved in chain-specific blocks 

- src/components/Proposals/ProposalPage/ApprovalCastVoteDialog/ApprovalCastVoteDialog.tsx
- src/components/shared/HumanAddress.jsx
Addresses issue in the linear ticket below.
> AGORA-2420

- src/app/proposals/components/AgoraGovCancel.tsx
- src/app/proposals/components/BravoGovCancel.tsx
- src/app/proposals/components/ProposalStateAdmin.tsx
- src/hooks/useGovernorAdmin.ts
- src/lib/contracts/common/interfaces/IGovernorContract.ts
https://linear.app/agora-app/issue/AGORA-3106/proposal-cancel-admin-only
> Hide Proposal Cancel for non admins

- src/app/delegates/components/EndorsedFilter.tsx
- src/app/delegates/page.jsx
- src/app/proposals/draft/[id]/page.tsx
- src/app/proposals/draft/components/DraftPreview.tsx
- src/app/proposals/draft/components/RequestSponsorshipForm.tsx
- src/app/proposals/draft/components/stages/DraftForm/DraftFormClient.tsx
- src/app/proposals/draft/components/stages/SubmitForm.tsx
- src/app/proposals/draft/utils/stages.ts
- src/app/proposals/sponsor/components/SocialProposalAction.tsx
- src/components/Delegates/DelegateCard/DelegateProfileImage.tsx
- src/components/Delegates/DelegateCard/DelegateSocialLinks.jsx
- src/components/Proposals/DraftProposals/DraftProposalCard.tsx
- src/lib/tenant/configs/ui/cyber.ts
- src/lib/tenant/tenantUI.ts
- Typed toggle configs 
- Expanded endorsed config in the tenant
> Tenant-level changes from the private branch 

- prisma/schema.prisma
Note that 36d782c03be1a6e3533f076019b5405ce80ad6a4 is actually at the base of PR#586
> Setup derive and pg prisma

- src/lib/tenant/configs/ui/scroll.ts
> Scroll admin page

- src/app/proposals/draft/components/dialogs/SponsorOnchainProposalDialog.tsx
- src/components/Proposals/ProposalPage/ApprovedTransactions/ApprovedTransactions.jsx
Updated the copy to reflect the indexer delay
> Proposal created dialog

- src/app/proposals/components/ProposalStateAdmin.tsx
> Implemented queue for approval proposals

- src/components/Proposals/ProposalPage/ApprovedTransactions/ProposalTransactionDisplay.tsx
Batch of updates following our initial merge earlier on Monday.
> Boost updates v2

- src/components/Votes/ProposalVotesList/ProposalNonVoterList.tsx
- src/components/shared/Switch.tsx
addresses
- font size
- border radius
- gap between rows of non-voters
> Updates non-voter list

- src/lib/tenant/tenantTokenFactory.ts
App side only, does not change contract token symbol
> Changes boost token name (BOOST -> BGUILD)

- src/lib/tenant/configs/ui/scroll.ts
> Scroll og image preview on the proposals page

- src/lib/tenant/configs/ui/scroll.ts
> Scroll info page links

- src/app/api/v1/relay/delegate/delegate.ts
- src/app/api/v1/relay/delegate/route.ts
- src/app/api/v1/relay/getRelayStatus.ts
- src/app/api/v1/relay/vote/castVote.ts
- src/components/Dialogs/DelegateDialog/DelegateDialog.tsx
- src/components/Votes/CastVoteInput/CastVoteContext.tsx
- src/components/Votes/CastVoteInput/CastVoteInput.tsx
- src/hooks/useNonce.ts
- src/hooks/useSponsoredDelegation.ts
- src/hooks/useSponsoredVoting.tsx
- src/lib/contracts/common/interfaces/ITokenContract.ts
- src/lib/tenant/configs/ui/ens.ts
- src/lib/tenant/tenantUI.ts
This PR only adds the functionality to delegate by signature. The UI is not updated according to the designs yet. We check the ui toggle: if gasless delegation is enabled, we use `delegateBySig`, otherwise we use the regular `delegate` function
> Gasless delegation

- src/app/proposals/draft/components/DeleteDraftButton.tsx
> small UI tweak for delete draft modal

- src/lib/tenant/configs/ui/ens.ts
- src/lib/tenant/configs/ui/uniswap.ts
Adding tenant-specific styles for ENS and Uniswap to enable email styling support.
> Tenant styles

- src/components/Delegates/Delegations/DelegationsContainer.tsx
Closes ENG-12 and I left a bunch more context in that ticket on JIRA.
https://voteagora.atlassian.net/browse/ENG-12
> ENG-12 - Change Delegate to/from Loading Limit

- src/app/proposals/components/ProposalStateAdmin.tsx
> Add state button for queued proposal for non-admins

- src/components/Proposals/ProposalPage/OPProposalPage/ProposalVotesSummaryDetails/ProposalVotesSummaryDetails.tsx
Only counting `For` votes for Uniswap quorum.
> Uniswap quorum display fix

- src/components/Proposals/DraftProposals/MyDraftProposals.tsx
- src/components/Proposals/ProposalPage/VotingTimelineChart/VotingTimelineChart.tsx
> Updates quorum count for uni

- src/components/Delegates/Delegations/DelegationsContainerWrapper.tsx
- src/components/Dialogs/DialogProvider/DialogProvider.tsx
- src/components/Header/DesktopProfileDropDown.tsx
- src/components/Header/MobileProfileDropDown.tsx
Note: 
- The "delegated to" displays SCW delegations only when a delegate has a delegate statement
> SCW Token balance + Delegated from 

- src/components/Dialogs/DelegateDialog/DelegateDialog.tsx
- src/components/Dialogs/DialogProvider/dialogs.tsx
- src/hooks/useTokenBalance.ts
> Fixing duplicate requests

- src/app/info/components/InfoHero.tsx
> Updates claim CTA on scroll info page

- src/components/Votes/ProposalVotesList/ProposalVotesList.tsx
Removes the issue of multiple state updates which was causing the page to crash. 
I believe in prod the redirect was happening, but it caught the error, then simply did not perform the page update as an alternative to showing a crashed page. While confusing, I guess it's a better experience. On local, we don't get this improvement, and the page simply crashes. This is how I was able to debug. 
I'm not 100% sure this will solve the problem, so I'm hoping deploying to a preview environment via this branch will help us check on the issue.
> Resolves redirect problem on OP

- src/components/Proposals/ProposalPage/OPProposalPage/OPProposalOptimisticPage.jsx
- src/components/Proposals/ProposalPage/OPProposalPage/ProposalVotesCard/OptimisticProposalVotesCard.tsx
> Fixed Optimistic proposal page

- src/components/Proposals/ProposalPage/ApprovedTransactions/ProposalTransactionDisplay.tsx
> Hotfix: Incorrectly referenced value in txn preview

- src/lib/tenant/configs/ui/derive.ts
To avoid confusion in navigation hide the derive proposal nav item.
https://voteagora.atlassian.net/browse/ENG-1003
> Hide derive proposals page

- src/app/page.tsx
- src/app/proposals/page.tsx
- src/components/Header/Navbar.jsx
- src/components/Proposals/ProposalsFilter/ProposalsFilter.tsx
- src/components/Proposals/ProposalsHome.tsx
- src/lib/tenant/configs/ui/derive.ts
> Add a dedicated /proposals route

- src/components/Proposals/ProposalPage/ProposalChart/ProposalChart.tsx
Just a small low priority UX update of something that was bothering me. Not sure if this is the behavior we want but it looks a lot better to me.
Before:
https://share.cleanshot.com/htccjvkr
After:
https://share.cleanshot.com/YlqYHc92
> UX update to expanding chart

- src/components/Proposals/ProposalPage/OPProposalApprovalPage/ApprovalVotesPanel/ApprovalVotesPanel.tsx
- src/components/Votes/ApprovalProposalVotesList/ApprovalProposalVotesList.tsx
- src/components/Votes/ProposalVotesList/ProposalNonVoterList.tsx
Issue was happening on Approval Proposals specifically due to its bigger votes panel header height causing it to get cut off because of the floating footer.
PR fixes this
> Fix votes panel too long cutting off on approval proposal

- src/components/Votes/ApprovalCastVoteButton/ApprovalCastVoteButton.tsx
- src/components/Votes/CastVoteInput/CastVoteInput.tsx
- src/hooks/useFetchAllForVoting.ts
One note is that I added this for approval voting as well which I am not sure was in the original intent or not as there are no specific designs for it
> Vote power based on creation time w/ tooltip

- src/app/proposals/components/ProposalStateAdmin.tsx
> Fixes issue targeting cancel button

- src/components/Delegates/Delegations/DelegationToRow.tsx
- src/components/Delegates/Delegations/DelegationsContainer.tsx
This PR removes the "Allowance" column in the "Delegated To" table, for all DAOs using "Full Delegation".  It brings it closer to the spirit of the protocol.
> Remove to balance for "Delegated To" table on Full Delegations

- src/components/Proposals/ProposalPage/OPProposalApprovalPage/OptionResultsPanel/OptionResultsPanel.tsx
- src/components/Votes/ApprovalProposalVotesList/ApprovalProposalVotesList.tsx
- src/components/Votes/ProposalVotesList/ProposalNonVoterList.tsx
Same as PR https://github.com/voteagora/agora-next/pull/751
Update needed to account for the increased height of the card coming from: https://github.com/voteagora/agora-next/pull/764
> Fix votes panel too long on approval proposal update

- src/components/Delegates/DelegateCard/DelegateCard.tsx
Tested on optimism preview, both mobile and desktop
> Mobile fix when on a delegate page can't take wallet actions

- prisma/schema.prisma
- src/app/proposals/draft/actions/createDraftProposal.ts
- src/app/proposals/draft/components/CustomTransactionForm.tsx
- src/app/proposals/draft/components/DraftPreview.tsx
- src/app/proposals/draft/components/TransferTransactionForm.tsx
- src/app/proposals/draft/components/stages/SubmitForm.tsx
- src/app/proposals/draft/schemas/DraftProposalSchema.ts
- src/app/proposals/draft/utils/getInputData.ts
- src/app/proposals/draft/utils/stages.ts
- src/app/proposals/sponsor/components/BasicProposalAction.tsx
- src/hooks/useGetVotes.ts
- src/lib/contracts/abis/UniswapToken.json
- src/lib/contracts/generated/factories/index.ts
- src/lib/contracts/generated/index.ts
- src/lib/tenant/configs/contracts/uniswap.ts
- src/lib/tenant/configs/ui/uniswap.ts
Todo: needs copy for "checklist"
> Adds PLM to uniswap

- src/app/layout.tsx
- src/app/proposals/draft/components/form/NumberInput.tsx
- src/lib/tenant/configs/ui/xai.ts
- src/lib/tenant/tenantUI.ts
* Add a new customisation letterSpacing
* Add 0.02em spacing for XAI
* fix tooltip in approval proposal to be text-secondary
> Feat: Add text spacing as tenant customisation 

- package.json
- src/app/api/common/delegateStatement/createDelegateStatement.ts
- src/components/Delegates/DelegateCardList/DelegateCard.tsx
- src/components/Delegates/DelegateStatement/DelegateStatement.jsx
- src/lib/sanitizationUtils.ts
- yarn.lock
This does both client and server side sanitization and leaves urls available for use
Tested against ENS thoroughly using the given eval statement. Also tested on uniswap the same way.
Tested on ENS using the markdown that we are meant to support from another users delegate statement to make sure this does not interfere with markdown. That user is here https://agora-next-kjr7yzj80-voteagora.vercel.app/delegates/0x0fcd2ead9943194eaa8bc6702a97555aad50455b
> ENG-1138 Add delegate statement html sanitization

- src/components/common/FilterListbox.tsx
Tested on https://agora-next-94sx30sub-voteagora.vercel.app/delegates
https://agora-next-optimism-git-pedro-eng-1153-xai-del-6a7e7d-voteagora.vercel.app/delegates
https://agora-next-uniswap-git-pedro-eng-1153-xai-dele-dfab61-voteagora.vercel.app/delegates
> Fix hard to read text in filter pill b/c of dark mode theming

- src/lib/voteUtils.ts
Tested with dev test wallet on:
https://agora-next-optimism-git-pedro-eng-1149-not-dis-c718ea-voteagora.vercel.app/proposals/76298930109016961673734608568752969826843280855214969572559472848313136347131
https://agora-next-optimism-git-pedro-eng-1149-not-dis-c718ea-voteagora.vercel.app/delegates/0x648bfc4db7e43e799a84d0f607af0b4298f932db
> Fix display voted options for own vote on Approval Proposal

- src/app/api/proposals/getVotesChart.ts
This PR fixes the chart data, by sorting it in the DB.  
This was tested by looking at a single fixed proposal on optimism locally.
> Fix chart tooltip

- src/app/delegates/page.jsx
- src/app/info/page.tsx
- src/components/Header/DesktopProfileDropDown.tsx
- src/components/Header/MobileProfileDropDown.tsx
- src/components/Hero/Hero.jsx
- src/components/Proposals/ProposalsHome.tsx
- src/lib/tenant/configs/ui/xai.ts
- src/lib/tenant/tenantTokenFactory.ts
- src/lib/tenant/tenantUI.ts
This PR supports XAI minor tweaks, and adds a parameter for the page to the `Hero` component.  We also change the label for "Balance" text.
> Make Hero Parametrized + Update text links symbol balance text for XAI

- src/components/Votes/CastVoteInput/CastVoteInput.tsx
Tested on:
https://agora-next-ens-git-pedro-eng-1140-ens-ended-vo-542935-voteagora.vercel.app/proposals/76121241460581498539558956630043503439383024967956373404044383542359545820056
https://agora-next-optimism-git-pedro-eng-1140-ens-end-7779e7-voteagora.vercel.app/proposals/69771922871899678295641228800065180752005123065337241545846173169617313270459
https://agora-next-optimism-git-pedro-eng-1140-ens-end-7779e7-voteagora.vercel.app/proposals/114198456650793912596888006877659015488795655065090503392438065090397296185351
> Fix ENS ended votes have two CTAs

- src/app/proposals/components/ProposalStateAdmin.tsx
Tested on https://agora-next-optimism-k57e2cfps-voteagora.vercel.app/proposals/21837554113321175128753313420738380328565785926226611271713131734865736260549
> Fix queue appearing on old proposals

- src/components/Admin/ProposalType.tsx
This PR is a minor patch, to reveal the functionality required to delete Optimistic Proposals
> Undisables Optimistic Proposals

- src/app/proposals/draft/components/ApprovalProposalForm.tsx
- src/app/proposals/draft/components/BasicProposalForm.tsx
This will simulate all possible combinations of winning options based on the selected criteria.
> Simulate transactions on the creation of approval proposals

- src/components/Delegates/DelegateCardList/DelegateCardList.tsx
- src/lib/sanitizationUtils.ts
tested against ENS and optimism
> Remove markdown from delegate previews

- src/app/proposals/draft/[id]/page.tsx
- src/app/proposals/draft/components/DraftPreview.tsx
- src/components/shared/Markdown/Markdown.tsx
* Have all hreaders to use primary and secondary
* Fix bold markdown stntax to use secondary
> Fix markdown colours for dark themes

- src/app/lib/hooks/useIsAdvancedUser.ts
- src/components/Dialogs/AdvancedDelegateDialog/SubdelegationRow.tsx
- src/components/Dialogs/PartialDelegateDialog/PartialDelegationEntry.tsx
Tested in https://agora-next-optimism-3j6cau274-voteagora.vercel.app/delegates delegate button with a allowListed wallet
> Partial delegation on mobile cannot type a dot

- src/__mocks__/fonts.ts
- src/components/Dialogs/DelegateDialog/DelegateDialog.tsx
- src/components/Dialogs/UndelegateDialog/UndelegateDialog.tsx
- src/components/Votes/CastVoteInput/CastVoteContext.test.tsx
- src/components/Votes/CastVoteInput/CastVoteContext.tsx
- src/components/Votes/CastVoteInput/CastVoteInput.tsx
- src/lib/tenant/configs/ui/ens.ts
- src/lib/tenant/configs/ui/uniswap.ts
- src/lib/tenant/tenantUI.ts
Tested with 2 wallets (one above the limit and one below) on:
https://agora-next-n0jqq9vv9-voteagora.vercel.app/proposals/67735687352329756707539052679943584106182461334310823374771499563155029489891
vs without the change in
https://agora-next-iw2b7lp9d-voteagora.vercel.app/proposals/76818066098263882979708920517360119767598381540188577320270510470572123084921
> Anti-spam limits into gas relays

- package.json
- src/app/delegates/[addressOrENSName]/page.tsx
- src/components/DelegateStatement/DelegateStatementForm.tsx
- src/components/Delegates/DelegateCard/DelegateCard.tsx
- src/components/Delegates/DelegateCard/DelegateCardEditProfile.tsx
- src/components/Delegates/DelegateCard/DelegateProfileImage.tsx
- src/components/Delegates/DelegateCard/SCWProfileImage.tsx
- src/components/Delegates/DelegateStatement/DelegateStatement.jsx
- src/components/Header/DesktopProfileDropDown.tsx
- src/components/Header/MobileProfileDropDown.tsx
- src/components/ui/tabs.tsx
- src/icons/logout.tsx
* Update profile dropdown to show either view profile or create delegate statement.
* Change edit profile to be in delegate page.
* Change styling of delegate page to match create delegate statement page.
* Remove delegate card stats in edit mode of profile.
* Update mobile dropdown to match dekstop behaviour
> Update profile dropdown and delegate info pages

- src/components/Header/DesktopProfileDropDown.tsx
- src/components/Votes/ApprovalProposalVotesList/ApprovalProposalSingleVote.tsx
- Fixes the misalignment in DesktopProfileDropdown
- ENS avatar wasn't showing in ApprovalProposalSingleVote: now fixed
Spot checked all ENS avatar instances throughout the app to make sure no other instances of misalignments or other weird issues.
> ENSAvatar misaligned in DesktopProfileDropdown

- src/lib/tenant/configs/ui/cyber.ts
Tested on cyber vercel [deployment](https://vercel.com/voteagora/agora-next-cyber/3tCiaMnxcTR6dejtDXEPM1EevBDJ/og)
> Update cyber config for open graph info

- src/app/info/components/GovernorSettingsParams.tsx
- src/app/info/components/GovernorSettingsProposalTypes.tsx
- src/lib/tenant/configs/ui/ens.ts
This PR:
- Sets a distinct "About Us" for UNI
- Fixes the proposal types table for UNI & ENS...sortof
> ENG-1387 ens info page missing proposal threshold quorum

- README.md
- src/app/Web3Provider.tsx
- src/lib/tenant/configs/contracts/ens.ts
- src/lib/tenant/configs/contracts/uniswap.ts
- src/lib/utils.ts
- src/lib/viem.ts
This PR adds `FORK_NODE_URL`, it's optional.  If it's set, it will be used instead of Alchemy.
> Enable Fork Mode

- src/app/api/common/delegates/getDelegates.ts
I think this really is just a one liner change. Maybe someone has cleaned up some of the complexity here already
> ENG-1359: Don't include optimistic proposals when calculating voter stats

- src/components/Proposals/ProposalPage/OPProposalApprovalPage/ApprovalProposalCriteria/ApprovalProposalCriteria.jsx
This is imacting all tenants except Op
> Add default quorum of 0 for pending proposals

- src/components/Proposals/ProposalPage/ApprovedTransactions/ProposalTransactionDisplay.tsx
> Fixed expanded txn overflow

- src/components/Proposals/ProposalPage/ApprovalCastVoteDialog/ApprovalCastVoteDialog.tsx
* Add max width to the option text
> Fix: Option overlapping the checkbox for approval voting.

- src/components/Header/MobileProfileDropDown.tsx
The portal on dao metrics(footer we see with token supply info) is causing an issue, even with sufficient z-index with fixed to counter this is not helping. `headlessui` has as portal prop on v2 but upgrading for this issue can cause more issues. 
considering we are removing  dao metrics component on mobile to be in drawer, this seems the best way to go forward for now. 
Testing notes:
Tested with couple of previews on metamask mobile.
> Fix: Mobile logout issue on mobile

- src/components/Dialogs/DialogProvider/DialogProvider.tsx
We should test as many modals as possible before merging this but confident that it won't break anything.
> Add max height to modal

- src/components/Dialogs/DialogProvider/DialogProvider.tsx
I broke it this morning when merged https://github.com/voteagora/agora-next/pull/929
> DialogProvider classname fix

- src/components/Proposals/ProposalPage/ApprovedTransactions/ProposalTransactionDisplay.tsx
- src/components/Proposals/ProposalPage/ProposalDescription/ProposalDescription.tsx
This PR fixes a few width overflows in mobile proposal page => some new, some old
> Fix width overflows in mobile proposal page

- src/app/proposals/draft/schemas/DraftProposalSchema.ts
Broke with a change from https://github.com/voteagora/agora-next/pull/913
> Change variables to optional

- src/components/Admin/GovernorSettings.tsx
* use useGovernorAdmin to fetch admin address to display above the manager address text.
> Feat: Add admin address in UI of admin page.

- src/app/api/common/delegates/getDelegates.ts
Only count finished proposals for voter stats
> ENG-1361: Fix voting activity during live proposal

- src/app/info/__tests__/GovernorSettingsParams.test.tsx
- src/app/info/components/GovernorSettingsParams.tsx
Requirement
If a value is greater than 24 hours, convert it to days + hours.
24 hours → 1 day
28 hours → 1 day, 4 hours
48 hours → 2 days
175 hours → 7 days, 7 hours
Note: Added mins if time is less than 24hrs.
> Feat: Update info page, contract params hours format

- src/app/api/votes/getVotes.ts
- src/app/lib/prisma.ts
- src/components/Dialogs/DialogProvider/dialogs.tsx
- src/components/Proposals/ProposalPage/ShareVoteDialog/ShareVoteDialog.tsx
- src/components/Votes/ApprovalCastVoteButton/ApprovalCastVoteButton.tsx
- src/components/Votes/CastVoteInput/CastVoteContext.tsx
- src/components/Votes/CastVoteInput/CastVoteInput.tsx
- src/hooks/useAdvancedVoting.tsx
- src/hooks/useFetchAllForVoting.ts
- src/lib/voteUtils.ts
- Adds a retry to prisma in case of error P1017 server has closed the connection
- Changes getAllForVoting function to use `Promise.allSettled` instead of `Promise.all` to make each returned prop optional.
> Better error handling getAllForVoting

- src/app/proposals/[proposal_id]/loading.tsx
- src/components/Header/Header.jsx
- src/components/Metrics/DAOMetricsHeader.jsx
- src/components/shared/AgoraLoader/AgoraLoader.tsx
* Add a delayed loader.
* Add loader for proposals page.
* Add border to nav and footer
> Updates to nav and footer

- src/components/Delegates/Delegations/DelegationsContainer.tsx
- src/lib/prismaUtils.ts
This PR reverts a prior patch, to attempt to fix undelegation.
> Remove ignoring 0x00000 delgatees

- src/app/delegates/[addressOrENSName]/page.tsx
Looked for other places where it might have been => this was the only one.
> Remove PI from page source code

- src/components/Header/MobileNavMenu.tsx
- src/components/Proposals/ProposalPage/CopelandProposalPage/OptionsResultsPanel/OptionsResultsPanel.tsx
Simple UI update to ad Info to mobile navbar.
May consider a more programmatic option in the future, or feeding navbar attributes from higher component level if navbar and mobile navbar always feature the same links.
Small change, self merge.
> Added toggle in the same fashion as the other ui toggles. Renders conditionally when active flag

- src/components/Delegates/DelegateCard/DelegateCardHeader.tsx
- src/components/Delegates/DelegateCardList/DelegateCard.tsx
- src/components/Delegates/DelegateCardList/DelegateTableRow.tsx
- src/components/Simulation/StructuredReport.tsx
- src/components/Votes/ApprovalProposalVotesList/ApprovalProposalSingleVote.tsx
- src/components/Votes/ProposalVotesList/ProposalSingleVote.tsx
> Small UX improvements

- src/app/proposals/draft/components/DraftPreview.tsx
- src/components/Proposals/ProposalPage/ApprovedTransactions/ProposalTransactionDisplay.tsx
- src/components/Proposals/ProposalStatus/ProposalStatus.jsx
- src/lib/proposalUtils.ts
- Passed proposal state after queued for > 10 days
- Allow proposal tx simulation with no "real actions"
- It was initially intentionally disabled because i didn't see value in having that. I changed my mind and can see the value now.
> Passed proposal state after queued for > 10 days

- src/app/api/common/delegates/getDelegates.ts
The import switch from #1002 earlier this week, is complaining about this.  This patch is an attempt at a fix for the issue.
> Fix component usage

- src/app/proposals/draft/components/ApprovalProposalForm.tsx
- src/app/proposals/draft/components/BasicProposalForm.tsx
- src/components/Proposals/ProposalPage/ApprovedTransactions/ProposalTransactionDisplay.tsx
- src/lib/seatbelt/checkProposal.ts
- src/lib/seatbelt/checks/check-targets-no-selfdestruct.ts
- src/lib/seatbelt/checks/check-targets-verified-etherscan.ts
- src/lib/seatbelt/encode-state.ts
- src/lib/seatbelt/simulate.ts
- Removed beta tag
- Performance improvements => no specific measurements taken but visibly faster in a 5-10x (varies from proposal to proposal) order of magnitude => one specific code section was **very** slow due mostly to dumb code `(fetchStorageLayout)`
- Added cache where possible
- 	Not caching the report specifically due to high size (> 2mb). Could do it but feels like overkill => the caches added in supporting functions make it fast
> Transaction simulation: cache + perf improvements + remove beta

- src/app/proposals/draft/components/ApprovalProposalForm.tsx
- src/app/proposals/draft/components/BasicProposalForm.tsx
- src/app/proposals/draft/components/TransferTransactionForm.tsx
- src/app/proposals/draft/components/form/AddressInput.tsx
- src/app/proposals/draft/components/stages/DraftForm/DraftFormClient.tsx
- src/app/proposals/draft/schemas/DraftProposalSchema.ts
- src/components/Proposals/ProposalPage/ApprovedTransactions/ProposalTransactionDisplay.tsx
- Fix validation for address => wasn't working
- Do validation onBlur instead of onSubmit
- Correct validation for calldata
- Display error message on failed tx simulation toast
- Fetch token decimals when custom token instead of defaulting to 18
> Better error display on tx simulation

- src/components/Delegates/DelegateCardList/DelegateToSelfBanner.tsx
- src/components/Header/EncourageDelegationDot.tsx
- src/components/Header/ProfileDropDownContent.tsx
* Remove the check for vp = 0; it can be the case since you delegated but has tokens.
> Fix: Delegation banner and dot showing since vp is zero.

- src/components/Delegates/DelegateStatement/TopIssues.tsx
If there is no text for top issues, use larger text for titles
> Fix: Trim top issues values in delegate statement.

- src/components/Votes/CastVoteInput/CastVoteInput.tsx
- src/hooks/useAdvancedVoting.tsx
- src/hooks/useStandardVoting.tsx
- Mobile voting UI/UX was unclear and did not handle voting transaction errors.
- Users did not always see clear prompts to approve transactions in their wallet.
- Error states (e.g., user rejection in MetaMask) were not always surfaced in the UI.
- Consolidated and improved error handling for all voting types.
- Added clear, actionable UI prompts for wallet approval and error states.
- Ensured error UI (with Cancel/Try Again) always appears on transaction failure or rejection.
- Improved mobile voting messages and button UX.
- Fixed bug where error state was not set if user rejected the transaction.
- No core voting logic was changed; all changes are UI/UX and error handling only.
- Cleaned up code to be minimal and maintainable.
- Manually tested on mobile and desktop:
- Voting flow …
> ENG-1756: improve mobile voting ux and error handling

- src/app/api/common/votes/getVotes.ts
- src/app/api/common/votes/vote.d.ts
- src/components/Votes/ProposalVotesList/ProposalSingleNonVoter.tsx
- src/components/Votes/ProposalVotesList/ProposalSingleVote.tsx
- src/components/Votes/ProposalVotesList/ProposalVotesList.tsx
- src/lib/constants.ts
- src/lib/voteUtils.ts
* Use avatar_url, name from atlas data
* Change USER threshold to 1000
Fixes: https://github.com/voteagora/op-atlas/issues/1111
> Use metadata for citizens from atlas

- src/components/Proposals/ProposalPage/OPProposalApprovalPage/ApprovalVotesPanel/HybridApprovalVotesPanel.tsx
- src/components/Proposals/ProposalPage/OPProposalPage/ProposalVotesCard/HybridOptimisticProposalVotesCard.tsx
- src/components/Proposals/ProposalPage/OPProposalPage/ProposalVotesCard/HybridStandardProposalVotesCard.tsx
- src/components/Proposals/ProposalPage/OPProposalPage/ProposalVotesCard/OffChainOptimisticProposalVotesCard.tsx
- src/components/common/VoteOnAtlas.tsx
Fixes BG on votes panel
From:
To:
> Fix: Remove bg from proposal votes panel to sections inside

- src/components/Proposals/ProposalPage/OPProposalPage/ProposalVotesSummary/HybridStandardProposalVotesSummary.tsx
- src/components/Proposals/ProposalPage/OPProposalPage/ProposalVotesSummary/HybridStandardVotesSummaryTooltip.tsx
- src/components/Proposals/ProposalPage/OPProposalPage/ProposalVotesSummaryDetails/ProposalVotesSummaryDetails.tsx
- src/components/common/StepperRow.tsx
- src/components/common/VotesBar.tsx
- src/lib/proposalUtils.ts
- src/lib/proposalUtils/proposalStatus.ts
- Add hover tooltip with comprehensive voting breakdown and timeline
- Create reusable StepperRow component for proposal timeline display
- Update VotesBar to support compact mode for tooltip usage
- Improve approval threshold calculation for hybrid standard proposals
- Add hover interaction for better UX on votes summary visualization
Ticket: https://voteagora.atlassian.net/browse/ENG-1852
> Enhance hybrid standard proposal votes summary with detailed tooltip

- CLAUDE.md
- src/app/api/common/proposals/fetchOffchainProposalsMap.ts
- src/app/api/common/proposals/getNeedsMyVoteProposals.ts
- src/app/api/common/proposals/getProposals.ts
- src/components/Votes/ProposalVotesList/ProposalSingleNonVoter.tsx
- src/components/Votes/ProposalVotesList/ProposalSingleVote.tsx
- Update getNeedsMyVoteProposals to query for offchain proposals matching onchain proposal IDs
- Create fetchOffchainProposalsMap utility function to reduce code duplication between getProposals and getNeedsMyVoteProposals
- Refactor getProposals to use the new utility function
- Add object cover to voted and not voted list avatars
> Add offchain proposal data to needs my vote api

- src/components/Proposals/Proposal/Proposal.tsx
- src/lib/proposalUtils.ts
* Fix condition for rendering proposal statuses
* Fix tiers to be sorted and divided by 100, since creation would return tier 65 as 6500
> Fix: Optimistic proposal status on proposals list

- src/components/Proposals/ProposalPage/OPProposalApprovalPage/ApprovalProposalCriteria/HybridApprovalCriteria.tsx
- src/components/Proposals/ProposalPage/OPProposalApprovalPage/ApprovalVotesPanel/HybridApprovalVotesPanel.tsx
- src/lib/proposalUtils.ts
- src/lib/proposalUtils/parseProposalResults.ts
* Consider unique voters from different tiers from API
* Use unique voters and calculate weighted percentage with eligible voters and weighted percentages.
* Update Hybrid approval voting panel to show quorum and current value
> Add Quorum to Hybrid approval proposals

- src/components/Votes/ProposalVotesList/ProposalSingleNonVoter.tsx
This PR fixes a bug in the hasn't voted view for Uniswap.
> Switch direct_vp -> voting_power

- src/lib/utils.ts
This PR handles a client-side crash when loading the "Hasn't voted" section of JH votes.
> Force BigInt / null-handling
