- src/components/Proposals/Proposal/OPStandardProposalStatus.jsx
> wojeth/agora-1458 Draw gray line even without any votes

- src/components/shared/ENSAvatar.jsx
Here is the preview link: https://agora-next-omtf1vp6t-voteagora.vercel.app/
> Fix: "When I switch wallets the ens image from the old wallet is not removed"

- src/components/Dialogs/DelegateDialog/DelegateDialog.tsx
Removing the info icon for standard delegation. Following the old page pattern, also I think it does not make sense to have this icon with standard delegation.
Here is the preview link: https://agora-next-k675d77o0-voteagora.vercel.app/
This would solve this bug: https://linear.app/agora-app/issue/AGORA-1574/myprofile-delegate-pop-up-is-displayed-after-the-phrase-your-total
Info icon for advanced delegation is being solved here: https://github.com/voteagora/agora-next/pull/110
> remove info icon for standard delegation

- src/app/api/analytics/metric/[metric_id]/[frequency]/getMetricsTS.ts
- src/app/api/analytics/vote/getProposalVoteCounts.ts
- Add proposal position (a monotonically increasing integer to be used in labels) to vote-counts
- Add proposal title (first line in description) to vote-counts
- Switch to latest multi-tenant schema for google analytics, dao engagement metrics, dao engagement votes
> Several Community Info Related Tweaks

- src/app/api/v1/retrofunding/rounds/[roundId]/ballots/[ballotCasterAddressOrEns]/submit/route.ts
The ballet submission address is not validated to be a badgeholder, because the `isBadgeholder` variable isn't extracted from the `fetchBadgeholder`. This allows anyone with a valid signature to submit ballots.
> Ensure isBadgeholder on ballot submission

- src/app/api/common/ballots/submitBallot.ts
- src/app/api/v1/retrofunding/rounds/[roundId]/ballots/[ballotCasterAddressOrEns]/submit/route.ts
Ballot submission returns an error for smart contract wallets, because the regex enforces the signature to be 130 hex characters (65 bytes), but EIP-1271 signatures are often far longer than that.
This PR fixes the signature validation bug by removing the exact signature length validation.
~Unfortunately the `ballotSubmittions.signature` column in the schema is a VARCHAR(255) which limits the ability to store full signatures in the database. Not sure what the downstream effects of this are, but I've updated the upsert to truncate the signature to fit in the column. If that breaks something downstream, we'll have to update the schema itself (i think https://github.com/voteagora/queries is a private repo?).~
> Support EIP-1271 signatures

- src/components/Dialogs/AdvancedDelegateDialog/useAdvancedDelegation.tsx
Delegation values were cached during component initialization. This PR ensures that the values are refreshed with every update.
> Fixing OP delegation

- src/components/Proposals/ProposalPage/OPProposalPage/ProposalVotesSummaryDetails/ProposalVotesSummaryDetails.tsx
Fixes: https://linear.app/agora-app/issue/AGORA-3243/before-somebody-votes-a-vote-shouldnt-say-nanpercent-it-should-just-be
> Don't show percentage if totalVotes = 0

- src/components/Delegates/DelegateCardList/DelegateCard.tsx
Bug - Delegates who have NEVER voted, have null participation, rather than 0% participation.
Fixes: https://linear.app/agora-app/issue/AGORA-3235/bug-delegates-who-have-never-voted-have-null-participation-rather-than
Supersedes https://github.com/voteagora/agora-next/pull/600
Two improvements on top of the old PR:
• Pushed from voteagor repo instead of my own fork
• FIxes "one problem is that while the data is loading it shows "0% participation" -- it doesn't look that bad, I pulled it down and ran it. Might be confusing though" (https://github.com/voteagora/agora-next/pull/600#discussion_r1840895551)
> Always show 0% participation

- src/components/Admin/GovernorSettings.tsx
Fixes both bugs reported in https://linear.app/agora-app/issue/AGORA-3309/bug-in-time-to-block-conversion-and-input-field-in-op-admin-voting :
If the user puts in 1 "hours", for "Voting Period", it broadcasts a message equal to 900, which is 30 minutes.  If the user puts in 1, it should broadcast 1800.
Additionally, in either field (Voting period or Voting delay).  The text box is awkward if you press backspace.  It won't let you clear the field.  The behaviour should be to allow the user to clear the field, in order to type a new number.  Perhaps gray out the button, if the field is empty.
https://github.com/user-attachments/assets/c5335c6e-43e2-48a8-b000-3e5ca055fa14
> Fix OP admin voting settings issues

- src/components/Votes/VoterHoverCard.tsx
Fixes https://linear.app/agora-app/issue/AGORA-3240/troubleshoot-fix-hover-card-that-never-loads
For the default message (when the statement is `null`), I just show `No statement` as in the screen recording below. But I'm not sure if there is a better message we can display here. All the content of a valid hover card seem to be dependent on `statement` being non-null so there is really nothing we can show as a fallback.
https://github.com/user-attachments/assets/724d1f22-6843-4b49-9cf4-38a6cf614912
> Fix voter card loading

- src/app/api/common/proposals/getProposals.ts
- src/app/delegates/[addressOrENSName]/page.tsx
- src/app/proposals/actions.tsx
- src/components/DelegateStatement/DelegateStatementForm.tsx
- src/components/Delegates/DelegateCard/DelegateCard.tsx
- src/lib/prismaUtils.ts
Was playing around with Boost and noticed that I was an inactive delegate even though there were no proposals.
Added a quick helper to fetch totalPrposals efficiently, then toggle based on that. 
Boost, no inactive delegare card, because less than 3 proposals.
ENS, Inactive card is there, because more than 3 proposals
OP, Inactive card is there, because more than 3 proposals
> [Improvement] Hide Delegate Card Activity if Absolute # of proposals < 3

- src/components/Dialogs/AdvancedDelegateDialog/SubdelegationRow.tsx
- src/components/Proposals/ProposalCreation/AddTransactionsDetails.tsx
- src/components/Proposals/ProposalCreation/ApprovalCriteriaRow.tsx
- src/components/Proposals/ProposalPage/OPProposalPage/ProposalVotesCard/OptimisticProposalVotesCard.tsx
Noticed that previous to this commit, the optimistic module on scroll said "OP". Now, we read token symbol from the tenant. See screenshot for new improvement. 
Went ahead and replaced all hardcoded 'OP' across the app.
> Replaces all instances of hardcoded 'OP'

- src/app/api/common/delegates/getDelegates.ts
- src/app/delegates/[addressOrENSName]/page.tsx
- src/app/delegates/actions.ts
- src/components/DelegateStatement/DelegateStatementForm.tsx
- src/components/Delegates/DelegateCard/DelegateCard.tsx
- src/hooks/useVotingStats.tsx
Resolves issue where 10 concurrent proposals wipes out voter participation, since we are using past 10 proposals to calculate participation percentage. The fix here introduces a change to the way we calculate participation. We now only count your participation over the last ten proposals that have ended -- meaning the endBlock is in the past. 
In this PR we start migrating away from the voter_stats view, all participation based calculations now rely on a new query from agora-next - NOT a materialized view like voter_stats. We still need voter_stats for things like a count of for, against, abstain, but we may phase this view out over time since it is extremely slow.
> ENG-874 -  Ignore active proposals in % Participation

- src/app/proposals/components/ProposalStateAdmin.tsx
This PR adds a cancelation button in-line with the execute button, for a queued proposal awaiting the timelock to pass prior to execution.
> Add cancel button

- src/components/Proposals/ProposalPage/OPProposalApprovalPage/OPProposalApprovalPage.tsx
- src/components/Proposals/ProposalPage/OPProposalPage/OPProposalOptimisticPage.jsx
- src/components/Proposals/ProposalPage/OPProposalPage/ProposalVotesBar/ProposalVotesBar.tsx
- src/components/Proposals/ProposalPage/OPProposalPage/StandardProposalPage.tsx
- src/components/Proposals/ProposalPage/VotingTimelineChart/VotingTimelineChart.tsx
Here’s the corrected version:
The problem: The voting chart displayed paginated results, so only the first page of votes was shown.
Short-term solution: Increase the page limit to 500.
Long-term solution: Update the underlying query to eliminate pagination.
> Temporary fix to the voting chart

- prisma/schema.prisma
- src/app/api/common/metrics/getMetrics.ts
- src/app/api/common/quorum/getQuorum.ts
- src/app/api/common/votableSupply/getVotableSupply.ts
- src/lib/prismaUtils.ts
This PR upgrades `deriveVotableSupply` to be contract aware.
We need to do this for all other tenants still, but that can be safely handled in a future PR.
> Upgrade votable supply to be token-contract aware - derive only

- src/hooks/useSmartAccountDerive.ts
- src/lib/tenant/configs/contracts/derive.ts
- src/lib/tenant/configs/ui/derive.ts
- src/lib/utils.ts
- src/lib/viem.ts
Pulled the latest version of Derive and updated all of Agora’s paths to match it. Note: still need to confirm that the conduit key is no longer needed.
> Updated RPC, Bundler, Paymaster paths and chain defs 

- src/hooks/useSponsoredDelegation.ts
- src/hooks/useSponsoredVoting.tsx
- src/lib/tenant/configs/ui/ens.ts
- src/lib/tenant/configs/ui/uniswap.ts
- src/lib/tenant/tenantUI.ts
This resolves the differences in signature composition between Uniswap (Bravo) and ENS (OZ). I have added an optional signature configuration to the UIGasRelayConfig tenant configuration.
> Fixed signature issues between ens and uniswap

- src/app/api/common/votes/getVotes.ts
This PR improves the speed of the has-not-voted modal.
This is the view at time of PR from PROD:
This is the view after the PR from local:
> Improve speed of has-not-voted & voter-results queries

- src/app/proposals/draft/utils/stages.ts
- src/components/Admin/GovernorSettings.tsx
- src/components/Admin/ProposalType.tsx
- src/components/Admin/ProposalTypeSettings.tsx
- src/lib/contracts/abis/ProposalTypesConfigurator.json
- src/lib/utils.ts
The original issue was "[setting proposal type in the UI hangs](https://voteagora.atlassian.net/browse/ENG-685)" --> the issue was that trying to update values on a given proposal type via the admin panel would silently crash giving the illusion that it was hanging forever.
The issue was that the ABI for the current proposalTypesConfigurator is incorrect – it’s missing the last param for setProposalType – module. 
The fix is to update the ABI and pass the module address to `setProposalType` so it does not silently crash.
I also noticed that it fails if you are not the admin of the PTC. It's not obvious who the admin is, so I added another bit of UI to show who the admin is so you know which wallet to switch to.
- boost (`0xA622279f76ddbed4f2CC986c09244262Dba8f4Ba`)
- cyber …
> Fixes PTC on admin

- src/lib/voteUtils.ts
Alright, this is a strange one. This was reported by a Discord user. 
On the approval vote, the options you voted for didn't show up. This used to work, but I can't find it in Git blame (probably there but eyes are hurting). 
So, the prolem was really simple, the `params` data for an approval vote is HEX encoded, and we were trying to parse the JSON directly, so it was going to `null` when passed to the client. 
This PR fixes this.
> Added the Approval Options back to the past votes

- src/lib/tenant/configs/ui/uniswap.ts
Uniswap had the "delegates/code-of-conduct" toggle enabled but no link for "code-of-conduct" causing the label to not be displayed due to the missing link.
Checked all others and Uniswap is the only one with these conditions.
This PR fixes this.
> Add Uniswap delegate code of conduct link

- src/components/Dialogs/DelegateDialog/DelegateDialog.tsx
- src/hooks/useSponsoredDelegation.ts
- src/lib/analytics.ts
Resolves two issues we were seeing with analytics:
- Some events were being tracked twice
- Some events were missing transaction hash
The issue came from the same place -- the sponsored (gas relay) delegation was counting events, and the regular delegation dialog was counting events, so they got counted twice. However, the dialog was trying to include the non-sponsored txHash, which didn't exist in the context of a sponsored delegation. When we were sending the event to the database, we used a fetch call, and needed to stringify the event so it could be sent across the wire. To do this, we used `JSON.stringify`, which I did not realize will remove all keys with undefined as a value. 
The fix is to....
- remove the double tracking
- add either sponsored OR nonsponsored txHash to the …
> Resolves delegation analytics fixes

- src/app/api/common/delegates/getDelegates.ts
- src/components/Delegates/DelegateCardList/DelegateCard.tsx
Resolves the issue of some voter participation numbers number showing up, even after minutes of waiting. The issue was twofold -- the `voterStats` query was returning no record if the voter had never voted yet, which meant that the voter stats data fetch returned 0 for the field `num_proposals`. `num_proposals` was intended to be the number of proposals submitted to the tenant, so even if the voter had never voted, this should still return the correct number. The reason is that the UI was then looking at this response, and if `num_proposals` was 0 it was skipping over the render and showing nothing. This was to prevent div/by/zero. 
The fix here is two-fold
1. fix the query to return correct num_proposals even if the voter has never voted
2. ~~return 0 instead of nothing if num_proposals …
> Updates stale voting states loading states (ENG-1022)

- src/components/Header/LogoLink.jsx
Adds badge to header when in a dev environment. Jeff made the suggestion somewhere in Slack. The idea is that it's not always clear if we are on prod or dev, especially when on a preview branch. This badge helps us know for certain which environment we are on.
> Adds dev badge

- src/app/api/common/governanceCalendar/getGovernanceCalendar.ts
- src/components/Proposals/CurrentGovernanceStage/CurrentGovernanceStage.tsx
- src/components/Proposals/ProposalsList/ProposalsList.tsx
Issue was happening due to ICS file lines not being correctly parsed. The summary wasn't being correctly set.
Check for reference the source calendar: https://calendar.google.com/calendar/u/0/embed?src=c_fnmtguh6noo6qgbni2gperid4k@group.calendar.google.com
Before:
After:
Before:
After:
Before:
After:
No voting cycle
Voting cycle which isn't review period or voting period. So there is no voting to begin or end yet. Removed "Voting" string and left just "Ends" string.
Same as above
> Fix calendar description not working correctly

- src/components/Proposals/ProposalPage/OPProposalPage/ProposalVotesSummary/ProposalVotesSummary.tsx
Tested on https://agora-next-optimism-ylst9502a-voteagora.vercel.app/proposals/88081957117197857131618413056069851464239155680037310590555441907734514873482
The fix implemented here was to basically just remove the bottom section of the card from the hoverTrigger allowing the cancelled button to be clickable. Another option would be to display the modal in the bottom instead of on top of the card.
Chose first option due to lower risk/impact but can switch to option 2 if we decide that it's better.
> Fix cancelled button not clickable

- src/app/delegates/components/DelegatorFilter.tsx
- src/app/delegates/components/EndorsedFilter.tsx
- src/app/delegates/components/IssuesFilter.tsx
- src/app/delegates/components/StakeholdersFilter.tsx
- src/components/Delegates/DelegateCardList/DelegateCardWrapper.tsx
- src/components/Delegates/DelegatesFilter/CitizensFilter.tsx
- src/components/Delegates/DelegatesFilter/DelegatesFilter.tsx
- src/components/Delegates/DelegatesSearch/DelegatesSearch.jsx
- src/components/Delegates/DelegatesTabs/DelegatesTabs.tsx
- src/components/common/FilterListbox.tsx
- Slightly reduced gap between filters + slightly reduced filters button font size + slightly reduced filters width size.
- Filters components refactored to use a common component to reduce tailwind maintenance
- Changing view doesn't trigger a new query
Test notes:
- Tested on https://agora-next-uniswap-git-pedro-eng-1094-uniswap-1c274e-voteagora.vercel.app/delegates
ENG-1094 + ENG-1093
> Fix voters page filters overflow + change view refreshing query

- spec/oas_v1.yaml
- src/app/api/common/delegates/delegate.d.ts
- src/app/api/common/delegates/getDelegates.ts
- src/app/api/common/utils/bigIntRatio.test.ts
- src/app/api/common/utils/bigIntRatio.ts
BigInt / BigInt in Js is truncated to nearest integer causing it to return zero. Adding a new util function calculateBigIntRatio to calculate relativeVotingPowerToVotableSupply
Added a flag in swagger to indicate `votingPowerRelativeToVotableSupply` is deprecated and returning the value in string format from a new key `relativeVotingPowerToVotableSupply`
Testing Notes:
Checked on https://agora-next-optimism-git-fix-eng-1078-votingpow-9253bf-voteagora.vercel.app/ with test wallet and can see relative vote power now
> Fix: Update relativeVotingPowerToVotableSupply calculation

- src/components/Delegates/DelegateCard/DelegateCardHeader.tsx
* Round of to 2 decimal points, this would reflect in inactive and active delegate cards
Testing notes: Tested locally. Once xai is merged we can use preview to test this on preview
> Fix: Round of Delegate info card participation percentage

- src/app/proposals/draft/components/DraftPreview.tsx
- src/components/shared/Markdown/Markdown.tsx
* Add overflow-x to be auto so tables in markdown does not cause the page content to overflow
* Add min-width to td so larger $ values dont wrap into multiple lines works till 10B and 1B with commas
Testing notes:
Tested with draft [proposal](https://agora-next-uniswap-git-fix-eng-1069-markdown-tables-voteagora.vercel.app/proposals/draft/481?stage=1
) preview on
> Fix: Markdown table overflow

- src/lib/voteUtils.ts
Tested against ENS. I do not believe any other tenants have snapshot votes, except etherfi which is a strange one. You may need to look at the jira ticket to navigate to the correct place in the app for the timestamp
> ENG-896 fix snapshot timestamps

- src/app/info/components/GovernorSettingsProposalTypes.tsx
This fixes the proposal type table view to include all relevant governors and format tokens accordingly.
Note that the 51% will be changed to 67% shortly.
> Fix Proposal Type Info Formatting

- jest.config.js
- package.json
- src/app/api/common/ballots/ballotAllocations.test.ts
- src/app/api/common/utils/bigIntRatio.test.ts
- vitest.config.mts
- yarn.lock
- Current Jest setup is incomplete and i have wasted ~2 hours trying to set it up. Vitest took me 5 minutes to do the whole config
- Jest: Poor ESM compatibility
- Vitest offers zero-config support for modern JavaScript features including ES modules, TypeScript, and JSX out of the box
- No need for complex Babel or TypeScript configuration that Jest requires
- 99.9% feature parity
- Easily reversible
- Vitest has a more clearer way of displaying the errors and failed tests
A few sources:
- https://www.56kode.com/posts/migration-from-jest-to-vitest/
- https://www.divotion.com/blog/why-vitest-might-be-better-than-jest-for-your-javascript-projects
- https://willcodefor.beer/posts/migrating-from-jest-to-vitest
Thoughts?
> Jest to vitest

- src/components/Proposals/ProposalPage/Charts/TimelineChart.tsx
This is a regression from https://github.com/voteagora/agora-next/commit/742e0e68bbac51599cbada93d58758b449f6b995#diff-586cd8bcb4021257470f2ef0ce06fe7cdea9fd74e19b71d39e3f5f2b13db6cb7L210
Adding back  reference line change
Testing Notes:
preview of OP below with [proposal](https://agora-next-optimism-git-fix-eng-1116-quorum-li-0ffce7-voteagora.vercel.app/proposals/71928632649116715308847337447543955907072794738294227130170691217045092512147) 
Preview on same [proposal](https://agora-next-optimism-git-fix-eng-1069-markdown-tables-voteagora.vercel.app/proposals/71928632649116715308847337447543955907072794738294227130170691217045092512147) an existing pr where the bug can be replicated
> Fix: Add Quorum reference line to visualisation

- src/app/api/common/delegations/getDelegations.ts
Tested against optimism as the ticket calls that out specifically.
Also manually tested against cyber as a FULL delegation tenant and derive as a PARTIAL delegation tenant
> Fix to get advanced delegations from alligator contract

- package.json
- src/components/Delegates/DelegateCardList/CitzenCardList.tsx
- src/components/Delegates/DelegateCardList/DelegateCard.tsx
- src/components/Delegates/DelegateCardList/DelegateCardList.tsx
- src/components/Delegates/DelegateCardList/DelegateCardWrapper.tsx
- src/components/Delegates/DelegateCardList/DelegateContent.tsx
- src/components/Delegates/DelegatesTabs/DelegatesTabs.tsx
- yarn.lock
The loading state was static variable and never changed. The actual refetch needed between switches never happened/started either.
This PR:
- Removes previous loading state variable
- Uses nuqs shallow option to trigger refetch (https://nuqs.47ng.com/docs/options#shallow)
- Uses React's useTransition hook as recommended by nuqs (https://nuqs.47ng.com/docs/options#transitions) to get loading states
> Fix switch between delegates and citizen tabs

- src/components/Admin/ProposalType.tsx
- src/components/Admin/ProposalTypeSettings.tsx
* Send empty strings inplace of name and description to delete a proposal type
* Add onDelete and onSuccessSetProposalType to handle client vs onchain state.
* use isClient flag as a way to remove the proposal type from UI
* On successful delete, use isSuccess flag to remove the proposal type from state so that ui reflects the change
Testing notes:
Tested on B3 [preview](https://agora-next-b3-git-sudheer-eng-1128-fix-the-del-8b0748-voteagora.vercel.app/admin) with admin wallet.
Scenarios:
1. Click on `Add another proposal type`
2. Click on  delete button without saving.
Expected: Ui should delete the newly added row without any creating a transaction.
1. Click on delete of `proposal type 5`
2. Confirm the transaction.
Expected: On success of transaction, the ui should remove the row from …
> Fix: Delete proposal type

- src/app/api/images/og/assets/shared.tsx
Tested on vercel [OG preview](https://vercel.com/voteagora/agora-next-xai/fHWYWfCGmZX8gs9dGb5p85WPq6Ur/og?path=delegates)
> Update XAI OG svg to match agora icon size

- src/app/api/common/metrics/getMetrics.ts
- src/app/api/common/metrics/route.ts
- src/app/layout.tsx
- src/components/Metrics/DAOMetricsHeader.jsx
- src/hooks/useDAOMetrics.js
* Change requests in metrics to be parallel
* Render Dao metrics component on client
* Add useGetMetrics hook for metrics data
* Add route for metrics to expose data to client
Since the proposal page is invalidated every 1 min but /info page is cached indefinitely there is a mismatch on the data. Changing this be client side request to sync the data between pages, since invalidating /info page seems unnecessary
> Change dao metrics to be client side component

- src/app/proposals/draft/components/stages/DraftForm/DraftFormClient.tsx
- src/app/proposals/draft/utils/__tests__/proposalTypes.ts
- src/app/proposals/draft/utils/proposalTypes.ts
* Filter options for tabs based on both types in config and contract
* Add a util to take contract types and return filtered proposal types
Testing Notes:
Tested with b3 by adding and removing approval voting.
> Feat: Change proposal type tabs to be based on config and types from contract

- src/lib/proposalUtils.ts
Tested by hardcoding the address with the issue to the query in getVotingPowerForProposalByAddress.
Issue was caused by the conversion between l1 block and arb block. Checked all uses of snapshotBlockNumber and it's safe to make the change made here. snapshotBlockNumber is used just a few times throughout the codebase for comparisons with snaps blocks. The snaps blocks are using arb blocks.
> XAI vote with vXAI showing 0 unexpectedly fix

- src/components/Delegates/Delegations/DelegationToRow.tsx
- src/components/Delegates/Delegations/DelegationsContainer.tsx
Add token balance column to delegated to table
Tested on [xai](https://agora-next-xai-git-sudheer-eng-1282-delegate-t-78d94d-voteagora.vercel.app/delegates/0x4c8ad181a8b891de450a50e31a003d0e530a6359) and [OP](https://agora-next-optimism-git-sudheer-eng-1282-deleg-5117b7-voteagora.vercel.app/delegates/0xd477cf2d2499620a2736bc9c0e7cf6939c29f4f9)
> Add balance of info in delegate to row

- src/components/shared/Switch.tsx
- tailwind.config.js
Update switcher styles with border and shadow for active state.
Testing notes:
Tested on xai, cyber and b3.
Changes can be seen on
1. Create draft page selection of type of proposal
2. In approval proposal creation form for threshold and top choices.
3. votes panel for has and hasn't voted.
> Update switcher styling globally

- src/components/Votes/CastVoteInput/CastVoteInput.tsx
Only show text field for reasoning when proposal is active
Tested on [OP](https://agora-next-optimism-git-sudheer-eng-1386-vote-6bb27e-voteagora.vercel.app/proposals/84511922734478887667300419900648701566511387783615524992018614345859900443455)
> Fix: Remove vote reason text field if proposal is not active

- src/app/api/common/notifications/updateNotificationPreferencesForAddress.ts
- src/app/delegates/actions.ts
- src/components/Notifications/SubscribeDialog.tsx
- src/hooks/useConnectedDelegate.ts
- src/hooks/useDelegate.tsx
* Add a tag with address for API
* Invalidate delegate tag on saving preferences
* Refetch client side settings on saving preferences
Testing notes:
1. Changed DB entry for a wallet with "prompt" as preferences, with email address linked in profile.
2. Open preview, should show the prompt. 
3. Click on notify me, wait for success message.
4. switch to voters tab, come back to proposals. Should not see prompt again.
Repeat same steps till 3 and  instead of step 4 refresh the page, should not see prompt again.
Same as both cases but have no mail address linked in delegate profile, and repeat the steps.
> Fix: Invalidate delegate cache on saving email preferences

- src/app/proposals/draft/components/stages/DraftForm/DraftFormClient.tsx
* For Uniswap and ENS there are no proposal types to show. In case of empty types remove the tab selector from UI
* change tab selector in UI to be grid col 1 for smaller screens so that proposal type tabs take up available space ([Ticket](https://voteagora.atlassian.net/browse/ENG-1434)).
> Fix: Uniswap and ENS proposal type selector showing empty selector

- src/app/proposals/components/AgoraOptimismGovCancel.tsx
The issue turned out to be the missing ‘0x’ prefix in the unformattedProposalData. When cancelWithModule was called, the bytecode didn’t match, and the proposal cancellation failed. This affected Optimistic and Approval proposals. The Standard proposal types were unaffected, as they used the standard cancel method.
Testing
> Fixing Optimistic / Approval module cancellation

- src/lib/tenant/configs/contracts/demo.ts
For partial delegation it's required to use AgoraToken__factory instead of ERC20__factory to get the correct ABI that supports it.
> use AgoraToken__Factory for demo tenant

- src/app/proposals/components/AgoraGovCancel.tsx
- src/app/proposals/components/AgoraGovExecute.tsx
- src/app/proposals/components/AgoraGovQueue.tsx
- src/app/proposals/components/AgoraOptimismGovCancel.tsx
- src/app/proposals/components/AgoraOptimismGovExecute.tsx
- src/app/proposals/components/AgoraOptimismGovQueue.tsx
- src/app/proposals/components/BravoGovCancel.tsx
- src/app/proposals/components/BravoGovExecute.tsx
- src/app/proposals/components/OZGovExecute.tsx
- src/app/proposals/components/OZGovQueue.tsx
* Use short error message from error obj instead of message which has quite a lot of data such as gas etc.
> Fix: Show short error messages on contract reverts

- src/app/api/common/delegations/getDelegations.ts
This PR changes out the delegate delegate-from table query, for Optimism.
Doing a full-scan of the 1.5Gb table is just too much to do.  There is a pending data-layer change that adds a materialized view to support.
* Compared from-delegate table for 1 large OP User vs Prod -> and visually inspected for deltas
* Wrote a python script to run the old and new sub-query for direct delegates, comparing the # of records for 1 large delegate.
> ENG-1524 tactical fix delegate from table

- src/components/Delegates/DelegateCard/DelegateActions.tsx
- src/components/Delegates/DelegateCard/PartialDelegateButton.tsx
- src/hooks/useGetDelegatee.ts
Partial delegation button always said "Delegate" without considering if it was already a delegatee
> Undelegate button for partial delegation

- src/app/api/common/delegations/getDelegations.ts
- src/lib/prismaUtils.ts
This PR filters out undelegation records from from the `findDelegatee`.
I ran it locally, set up the case where I delegated and then undelegated using 0xa622279f76ddbed4f2cc986c09244262dba8f4ba, on one tenant.
> Add filter to remove undelegation from `findDelegatee`

- src/components/Delegates/DelegateCardList/DelegateTableRow.tsx
* Consider total proposal in calculating participation percentage. This matches the card layout calculation
Jira: [Ticket](https://voteagora.atlassian.net/browse/ENG-1527) 
Tested on scroll:
> Fix: Delegate participation in delegates table.

- src/components/Proposals/Proposal/OPOptimisticProposalStatus.jsx
- src/components/Proposals/ProposalPage/OPProposalPage/OPProposalOptimisticPage.jsx
Pguild: 
Op existing proposals
> Fix: Use token decimal in conversion for optimistic proposals

- src/app/proposals/draft/utils/getInputData.ts
- src/lib/seatbelt/simulate.ts
- No op function should target timelock instead of governor
- Tested by running tenderly simulation against execution
- ERC721 support for seatbelt
- Tested by running simulation on pguild
> No op function should target timelock instead of governor

- src/components/Proposals/ProposalPage/ApprovedTransactions/ProposalTransactionDisplay.tsx
- src/lib/seatbelt/checks/check-decode-calldata.ts
- src/lib/utils.ts
This adds additional functionality to the action preview to show param variable names and values into the preview. If there are more than 3 parameters in the function signature, it will produce an ellipsis, but will still be seen from the tooltip.
The getFunctionSignature now returns an interface with the function name, the parameters in tuple format [name, value] if they exist, and a function to build a string representation of the functionSignature (used in the tooltip).
> ENG-1571-Action-preview-truncates-to-only-function-call-and-doesn-t-show-params

- src/components/Admin/GovernorSettings.tsx
* Seperate the toasts useEffect so voting period and delay act with thier own changes.
* Issue: since the second time a transaction is created, this triggers a change in dependencies of useEffect and enters success of previous transaction block as well. causing a duplicate toast.
> Fix: Duplicate toast on governor settings.

- src/components/Proposals/Proposal/HybridStandardProposalStatus.tsx
This pull request addresses an issue with inconsistent width by pinning the value to `w-52`. This change helps maintain a consistent layout. No other changes were introduced.
> Fix width issue by pinning to w-52
